name: Check Markdown Markup

on: [push]

jobs:
  markdown-lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: Document Document-de Document-es Document-fr Document-ja Document-ko Document-ru Document-zhtw Document-zhcn
          config_file: ".markdownlint.json"
          ignore_files: "Tools, node_modules"